# .github/workflows/build-and-push.yml (최종 완성본)

name: Build, Push, and Deploy to Google Cloud Run

on:
    push:
        branches:
            - devops

env:
    GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    GAR_LOCATION: asia-northeast3
    BACKEND_SERVICE_NAME: live-voice-agent-backend
    FRONTEND_SERVICE_NAME: live-voice-agent-frontend

jobs:
    build-push-deploy:
        name: Build, Push, and Deploy
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v2

            - name: Configure Docker
              run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

            - name: Build and push Backend image
              run: |
                  docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.BACKEND_SERVICE_NAME }}/image:latest ./backend
                  docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.BACKEND_SERVICE_NAME }}/image:latest

            - name: Build and push Frontend image
              run: |
                  docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.FRONTEND_SERVICE_NAME }}/image:latest ./frontend
                  docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.FRONTEND_SERVICE_NAME }}/image:latest

            # --- 백엔드 배포 부분 수정 ---
            - name: Deploy Backend to Cloud Run
              uses: google-github-actions/deploy-cloudrun@v2
              with:
                  service: ${{ env.BACKEND_SERVICE_NAME }}
                  region: ${{ env.GAR_LOCATION }}
                  image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.BACKEND_SERVICE_NAME }}/image:latest

                  # --- 이 아랫부분이 추가되었습니다! ---
                  # gcloud 명령어의 '--set-env-vars' 옵션에 해당합니다.
                  env_vars: |-
                      VOICE_LIVE_MODEL=gpt-4o
                      AZURE_VOICE_LIVE_API_VERSION=2025-05-01-preview

                  # gcloud 명령어의 '--set-secrets' 옵션에 해당합니다.
                  secrets: |-
                      AZURE_VOICE_LIVE_API_KEY=azure-voice-live-api-key:latest
                      AZURE_VOICE_LIVE_ENDPOINT=azure-voice-live-endpoint:latest

            # 프론트엔드는 별도의 환경 변수나 비밀 키가 필요 없으므로 그대로 둡니다.
            - name: Deploy Frontend to Cloud Run
              uses: google-github-actions/deploy-cloudrun@v2
              with:
                  service: ${{ env.FRONTEND_SERVICE_NAME }}
                  region: ${{ env.GAR_LOCATION }}
                  image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.FRONTEND_SERVICE_NAME }}/image:latest
